dist: trusty
sudo: false
language: csharp
mono: none
dotnet: 1.0.1
services:
  - docker
script:    
  - dotnet restore ./Domain.Tests/Domain.Tests.csproj
  - dotnet test ./Domain.Tests/Domain.Tests.csproj
  - dotnet restore ./Application.Tests/Application.Tests.csproj
  - dotnet test ./Application.Tests/Application.Tests.csproj
after_success: 
 - sh buildscripts/build_publish_docker_image.sh 